INSERT INTO CARRIER (NAME, PASSWORD) VALUES ('Seur', 'test');
INSERT INTO CARRIER (NAME, PASSWORD) VALUES ('Mrw', 'test');
INSERT INTO CARRIER (NAME, PASSWORD) VALUES ('Correos', 'test');

INSERT INTO PARCEL (TRACKING_NUMBER, CARRIER_ID, STATE) VALUES ('SEUR1234XYZ', 1, 'En tránsito');
INSERT INTO PARCEL (TRACKING_NUMBER, CARRIER_ID, STATE) VALUES ('SEUR5678ABC', 1, 'Entregado');
INSERT INTO PARCEL (TRACKING_NUMBER, CARRIER_ID, STATE) VALUES ('SEUR9999ttt', 1, 'Error en la entrega');

INSERT INTO PARCEL (TRACKING_NUMBER, CARRIER_ID, STATE) VALUES ('123', 2, 'En tránsito');
INSERT INTO PARCEL (TRACKING_NUMBER, CARRIER_ID, STATE) VALUES ('456', 2, 'Entregado');
INSERT INTO PARCEL (TRACKING_NUMBER, CARRIER_ID, STATE) VALUES ('789', 2, 'Error en la entrega');


INSERT INTO PARCEL (TRACKING_NUMBER, CARRIER_ID, STATE) VALUES ('ABC123', 3, 'En tránsito');
INSERT INTO PARCEL (TRACKING_NUMBER, CARRIER_ID, STATE) VALUES ('456ZZZ', 3, 'Entregado');
INSERT INTO PARCEL (TRACKING_NUMBER, CARRIER_ID, STATE) VALUES ('789888', 3, 'Error en la entrega');