INSERT INTO CARRIER (NAME, PASSWORD) VALUES ('seur', 'test');
INSERT INTO CARRIER (NAME, PASSWORD) VALUES ('mrw', 'test');
INSERT INTO CARRIER (NAME, PASSWORD) VALUES ('correos', 'test');


-- INSERT INTO PARCEL (TRACKING_NUMBER, CARRIER_ID, STATUS) VALUES ('SEUR1234XYZ', 1, 'En tránsito');
-- INSERT INTO PARCEL (TRACKING_NUMBER, CARRIER_ID, STATUS) VALUES ('SEUR5678ABC', 1, 'Entregado');
-- INSERT INTO PARCEL (TRACKING_NUMBER, CARRIER_ID, STATUS) VALUES ('SEUR9999ttt', 1, 'Error en la entrega');
--
-- INSERT INTO PARCEL (TRACKING_NUMBER, CARRIER_ID, STATUS) VALUES ('123', 2, 'En tránsito');
-- INSERT INTO PARCEL (TRACKING_NUMBER, CARRIER_ID, STATUS) VALUES ('456', 2, 'Entregado');
-- INSERT INTO PARCEL (TRACKING_NUMBER, CARRIER_ID, STATUS) VALUES ('789', 2, 'Error en la entrega');
--
--
-- INSERT INTO PARCEL (TRACKING_NUMBER, CARRIER_ID, STATUS) VALUES ('ABC123', 3, 'En tránsito');
-- INSERT INTO PARCEL (TRACKING_NUMBER, CARRIER_ID, STATUS) VALUES ('456ZZZ', 3, 'Entregado');
-- INSERT INTO PARCEL (TRACKING_NUMBER, CARRIER_ID, STATUS) VALUES ('789888', 3, 'Error en la entrega');