CREATE TABLE Carrier (
CarrierId INTEGER NOT NULL AUTO_INCREMENT,
CarrierName VARCHAR NOT NULL,
Password VARCHAR NOT NULL,
PRIMARY KEY (CarrierId)

)


CREATE TABLE Order (
OrderId INTEGER NOT NULL AUTO_INCREMENT,
OrderNumber INTEGER NOT NULL,
CarrierId INTEGER NOT NULL AUTO_INCREMENT,
State VARCHAR NOT NULL
PRIMARY KEY (Order)

)
