CREATE TABLE CARRIER 
(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(250) NOT NULL,
password VARCHAR(50) NOT NULL
);

CREATE TABLE PARCEL 
(
id INT AUTO_INCREMENT PRIMARY KEY,
track_number VARCHAR(250) NOT NULL,
status VARCHAR(50) NOT NULL,
carrier_id INT,
 foreign key (carrier_id) references CARRIER(id)
);

