CREATE TABLE CARRIER
(
    ID       INT                NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME     VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(50)        NOT NULL
);

CREATE TABLE PARCEL
(
    ID              INT                NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TRACKING_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    CARRIER_ID      INT                NOT NULL AUTO_INCREMENT,
    STATE           VARCHAR(50)        NOT NULL,
    FOREIGN KEY (CARRIER_ID) REFERENCES CARRIER (ID),
    CHECK (STATE IN ('En tránsito', 'Entregado', 'Error en la entrega'))
);
